[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hype_or_flop = "E4ZzS3D1XA1jKLYu4BssDVUXsZzPLiuBDabumAYFhAiC"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
